---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: external-dns
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: external-dns-pi
        property: token
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.4
    helm:
      valuesObject:
        fullnameOverride: external-dns
        policy: sync
        registry: txt
        txtOwnerId: kubernetes
        provider:
          name: cloudflare
        sources:
          - service
          - ingress
          - crd
        annotationFilter: "external-dns.custom/type in (public, private)"
        env:
          - name: CF_API_TOKEN
            valueFromSecret:
              name: external-dns
              key: CF_API_TOKEN
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
