---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns 
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.4 # Use your desired version
    helm:
      values: |  
        external-dns:
          fullnameOverride: external-dns
          policy: sync
          txtSuffix: ".external-dns"
          txtOwnerId: kubernetes
          crd:
            create: true
          sources:
            - service
            - ingress
            - crd
          provider: cloudflare
          cloudflare:
            secretName: cloudflare-api-key # Reference the intended Secret
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-key
                  key: apiKey
          annotationFilter: "external-dns.custom/type in (public, private)"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
